### ISSUE TITLE
Backport 4.0.0 to Rails 4.2

### ISSUE THREAD

**Issue by twohlix** [lserman/maia#4]
It would be useful to backport FCM support to Rails 4.2. I did this but it isn't really a pull request, it would mostly be a gem build and alternate branch request which I'm unsure how to do that.

https://github.com/twohlix/maia/tree/rails4-fcm is the latest branch, and really its just 1 commit to do the backporting: https://github.com/twohlix/maia/commit/5b806a18dd4867fd4bcdecbc14973d2bb7e8302b

Also I dropped the version to 3.0.0 (unused from what i see on rubygems) since 4.0.0 is for Rails5 only. I'll be doing staged environment testing this next week.

**Comment by lserman** [comment]
Hmm I'll have to see if we can just add something to .travis.yml that will maintain one build for both branches, that would be a nice solution if it's possible

**Comment by lserman** [comment]
Actually just having a separate .travis.yml on your branch would work fine I think... I don't think you can make a PR for a new branch can you? Do you want me to make a new branch in this repo and then you can rebase onto that and submit a PR to that branch?

**Comment by twohlix** [comment]
Exactly correct that I cannot create a new branch via PR. If you'd like to just cut a branch from the current master head and name it whatever you feel is right for this I can PR against that. That would be excellent.

**Comment by lserman** [comment]
Just pushed a rails4-x branch

**Comment by twohlix** [comment]
Thanks, have a PR out for ya

**Comment by twohlix** [comment]
FYI, Things have been sending fine through the FCM service using the changes in the PR.

**Comment by twohlix** [comment]
PR Merged addresses this issue. Thanks @lserman
